config/routes.rb
# frozen_string_literal: true

Webapp::Application.routes.draw do
  resources :assignments, only: [] do
    collection do
      get :knight
    end
  end

  resources :regions, except: [:show]

  resources :cell_carriers do as_routes end
  resources :transport_types do as_routes end

  resources :scale_types

  resources :absences do
    collection do
      get :all
    end
  end

  resources :logs do
    collection do
      get :by_day
      get :tardy
      get :last_ten
      get :open
      get :todo
      get :mine_past
      get :mine_upcoming
      get :being_covered
      get :new_absence
      get :create_absence
      get :receipt
      get :index
      get :edit
      get :update
      get :create
      get :destroy
      get :stats_service
      get :stats
      get :export
    end
    member do
      get :take
      get :leave
    end
  end

  resources :schedule_chains do
    collection do
      get :today
      get :tomorrow
      get :yesterday
      get :open
      get :open_old
      get :mine
      get :mine_old
      get :take
      get :leave
      get :index
      get :edit
      get :update
      get :create
      get :destroy
    end
    # member do
    #  get :show
    # end
  end

  resources :locations do
    collection do
      get :recipients
      get :hubs
      get :sellers
      get :buyers
      get :index
      get :edit
      get :update
      get :create
      get :destroy
    end

    member do
      get :hud
    end
  end

  devise_for :volunteers, :controllers => { :sessions => 'sessions' }

  resources :volunteers do
    collection do
      get :home
      get :unassigned
      get :shiftless
      get :shiftless_old
      get :active
      get :inactive
      get :need_training
      get :super_admin
      get :region_admin
      get :stats
      get :shift_stats
      get :switch_user
      get :knight
      get :index
      get :edit
      get :update
      get :create
      get :destroy
      get :assign
    end
    member do
      get :reactivate
    end
  end

  resource :waiver, only: [:new, :create]

  namespace :region_admin do
    resources :donors, only: [:index]

    resources :food_types, only: [:index, :new, :create, :edit, :update, :destroy]
  end

  devise_scope :volunteer do
    authenticated do
      root to: 'volunteers#home'
    end

    unauthenticated do
      root to: 'sessions#new', as: :unauthenticated_root
    end
  end
end

app/models/volunteer.rb
# frozen_string_literal: true

# Volunteer is the god object for BFR Robot
class Volunteer < ActiveRecord::Base
  default_scope { order('volunteers.name ASC').where(active: true) }
  scope :in_regions, ->(region_ids) { joins(:regions).where(regions: { id: Array.wrap(region_ids) }).uniq }
  scope :completed_any, -> { joins(log_volunteers: [:log]).where(logs: { complete: true }) }

  # Return all voluneers in specified regions that do not have completed logs
  scope :needing_training, (lambda do |regions|
    completed_logs_in_region = Volunteer.in_regions(regions).completed_any

    in_regions(regions).where(
      'volunteers.id NOT IN (?)',
      completed_logs_in_region.count.zero? ? [0] : completed_logs_in_region
    )
  end)

  belongs_to :transport_type
  belongs_to :cell_carrier
  belongs_to :requested_region, class_name: 'Region'

  has_many :absences, dependent: :destroy
  has_many :assignments
  has_many :regions, through: :assignments

  has_many :schedule_volunteers
  has_many :schedule_chains, through: :schedule_volunteers,
                             conditions: { 'schedule_volunteers.active' => true }
  has_many :prior_schedules, through: :schedule_volunteers,
                             conditions: { 'schedule_volunteers.active' => false },
                             class_name: 'ScheduleChain'

  has_many :log_volunteers
  has_many :logs, through: :log_volunteers,
                  conditions: { log_volunteers: { active: true } }
  has_many :completed_logs, through: :log_volunteers,
                            conditions: { logs: { complete: true } },
                            class_name: 'Log', source: :log

  has_many :prior_logs, through: :log_volunteers,
                        conditions: { 'log_volunteers.active' => false },
                        class_name: 'Log'

  attr_accessible :pre_reminders_too, :region_ids, :password,
                  :password_confirmation, :remember_me, :admin_notes, :email,
                  :has_car, :is_disabled, :name, :on_email_list, :phone,
                  :pickup_prefs, :preferred_contact, :transport, :sms_too,
                  :transport_type, :cell_carrier, :cell_carrier_id,
                  :transport_type_id, :photo, :get_sncs_email,
                  :assigned, :requested_region_id, :authentication_token

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  #has_attached_file :photo,
  #                  styles: { thumb: '50x50', small: '200x200', medium: '500x500' },
  #                  s3_credentials: { bucket: 'boulder-food-rescue-robot-volunteer-photo' }
  #validates_attachment_file_name :photo, matches: [/png\Z/, /jpe?g\Z/, /gif\Z/]

  before_save :ensure_authentication_token
  after_save :auto_assign_region

  scope :not_super_admin, -> { where(admin: false) }
  scope :super_admin, -> { where(admin: true) }
  scope :unassigned, -> { includes(:assignments).where( assignments: { volunteer_id: nil }) }
  scope :assigned_to_regions, -> (admin_region_ids) { joins(:assignments).where(assignments: { region_id: admin_region_ids }) }

  # more trustworthy and self.assigned? attribute?
  def unassigned?
    assignments.empty?
  end

  def needs_training?
    logs.where(complete: true).count.zero?
  end

  # devise overrides to deal with not approved stuff
  # https://github.com/plataformatec/devise/wiki/How-To:-Require-admin-to-activate-account-before-sign_in
  def active_for_authentication?
    super && assigned?
  end

  def inactive_message
    if assigned?
      super
    else
      :not_assigned
    end
  end

  def self.send_reset_password_instructions(attributes = {})
    recoverable = find_or_initialize_with_errors(reset_password_keys, attributes, :not_found)
    if !recoverable.assigned?
      recoverable.errors[:base] << I18n.t('devise.failure.not_approved')
    elsif recoverable.persisted?
      recoverable.send_reset_password_instructions
    end
    recoverable
  end

  def sms_email
    return nil if cell_carrier.nil? || phone.nil? || phone.strip == ''
    return nil unless phone.tr('^0-9', '') =~ /^(\d{10})$/
    # a little scary that we're blindly assuming the format is reasonable, but only admin can edit it...
    sprintf(cell_carrier.format, $1)
  end

  def ensure_authentication_token
    return unless authentication_token.blank?

    self.authentication_token = generate_authentication_token
    save
  end

  def reset_authentication_token
    self.authentication_token = generate_authentication_token
    save
  end

  ### REGION-RELATED METHODS

  # Admin info accessors
  def super_admin?
    admin
  end

  # if first argument is nil, checks if they're a region admin
  # of any kind. otherwise, tests if they're a admin for the given region
  # if strict is false, will not return true if they're a super admin
  def region_admin?(region = nil, strict = true)
    return true if !strict && super_admin?

    admin_regions_ids = admin_region_ids(strict)

    if region.nil?
      return true unless admin_regions_ids.empty?
    elsif admin_regions_ids.include?(region.id)
      return true
    end

    false
  end

  # non-strict version of the above
  def any_admin?(region = nil)
    region_admin?(region, false)
  end

  def main_region?
    !main_region.nil?
  end

  def main_region
    regions.first
  end

  def admin_region_ids(strict = false)
    admin_regions(strict).collect(&:id)
  end

  def admin_regions(strict = false)
    return Region.all if super_admin? && !strict

    assignments.eager_load(:region)
               .where(admin: true)
               .collect(&:region)
               .compact
  end

  def in_region?(region_id)
    region_ids.include? region_id
  end

  def current_absences
    today = Date.today
    absences.where('start_date < ? AND stop_date > ?', today, today)
  end

  def region_names
    assignments.flat_map { |a| "#{a.region.try(:name)}#{a.admin ? '*' : ''}" }.uniq.join(',')
  end

  ### CLASS METHODS

  def self.with_regions_for_select(vols)
    vols.collect { |v| ["#{v.name} ['#{v.region_names}']", v.id] }
  end

  def self.active(region_ids = nil, ndays = 90)
    query = joins(:logs).group('volunteers.id')
                        .having('max(logs.when) > ?', Time.zone.today - ndays)

    if region_ids.present?
      query.joins(:regions)
           .where(regions: { id: region_ids })
    else
      query
    end
  end

  def self.inactive(region_ids = nil)
    query = where(active: false)

    if region_ids.present?
      query.joins(:regions).where(regions: { id: region_ids }).group('volunteers.id')
    else
      query
    end
  end

  def self.all_for_region(region_id)
    includes(:regions)
      .where(regions: { id: region_id })
      .compact
  end

  def self.active_but_shiftless(region_ids)
    includes(:regions)
      .where(regions: { id: region_ids })
      .where('regions.id' => region_ids)
      .where('(SELECT COUNT(*) FROM schedule_chains ' \
            'INNER JOIN schedule_volunteers ON ' \
            'schedule_chains.id = schedule_volunteers.schedule_chain_id ' \
            "WHERE schedule_chains.active = 't' " \
            'AND schedule_volunteers.volunteer_id = volunteers.id ' \
            "AND schedule_volunteers.active = 't') = 0")
  end

  private

  # better first-time experience: if there is only one region, add the user to
  # that one automatically when they sign up
  def auto_assign_region
    if Region.count == 1 && regions.count.zero?
      Assignment.add_volunteer_to_region self, Region.first
      logger.info "Automatically assigned new user to region #{regions.first.name}"
    end
  end

  def generate_authentication_token
    loop do
      token = Devise.friendly_token
      break token unless Volunteer.where(authentication_token: token).first
    end
  end
end

app/helpers/volunteers_helper.rb
# frozen_string_literal: true

module VolunteersHelper
  def volunteer_photo_column(record)
    return '' if record.photo_file_name.nil?
    link_to image_tag(record.photo(:thumb)){ record.photo(:medium) }
  end

  # RB 3-23-2018: Return volunteers that are unassigned
  # and in current volunteer's region(s).
  # All super admins are filtered out for security purposes
  def my_admin_volunteers
    return Volunteer.all if current_volunteer.super_admin?

    unassigned = Volunteer.not_super_admin
                          .unassigned

    volunteers_in_regions = Volunteer.not_super_admin
                                     .assigned_to_regions(current_volunteer.admin_region_ids)

    (volunteers_in_regions + unassigned).uniq
  end

  def adminable_active_volunteers
    return Volunteer.active if current_volunteer.super_admin?
    Volunteer.not_super_admin.active(current_volunteer.region_ids)
  end
end

app/views/volunteers/_datepicker.html.erb
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/flatpickr/4.5.2/themes/airbnb.css">
<!--[if IE 9]>
  <link rel="stylesheet" type="text/css" href="https://npmcdn.com/flatpickr/dist/ie.css">
<![endif]-->

<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>

<% content_for :scripts do %>
  <script type="text/javascript">
    $(document).ready(function() {
      flatpickr(".datepicker", {
        dateFormat: "Y-n-j",
        allowInput: true,
        altInput: true,
        altFormat: "F j, Y",
        onOpen: function(selectedDates, dateStr, instance) {
          instance.setDate(instance.input.value, true);
        }
      });
    });
  </script>
<% end %>

app/views/volunteers/_form.html.erb
<%= form_for @volunteer do |f| %>

  <table class="table table-striped">

    <tr>
      <td>
        <label for="volunteer_name">
          Name
        </label>
      </td>
      <td><%= f.text_field(:name, class: "form-control") %></td>
    </tr>

    <tr>
      <td>
        <label for="volunteer_photo">
          Photo
        </label>
      </td>
      <td>
        <%= image_tag @volunteer.photo.url(:thumb), alt: "#{@volunteer.name} Photo" %>
        <%= f.file_field(:photo) %>
      </td>
    </tr>

    <tr>
      <td>
        <label for="">
          Pickup Stats
        </label>
      </td>
      <td>
        <details>
          <table class="table table-striped">
            <thead>
              <tr>
                <th>When</th>
                <th>Donor</th>
                <th>Transported With</th>
                <th>Time Spent</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <% @volunteer.completed_logs.each do |log| %>
                <tr>
                  <td><%= log.when %></td>
                  <td><%= log.donor.try(:name) %></td>
                  <td><%= log.transport_type.try(:name) %></td>
                  <td><%= log.hours_spent %></td>
                  <td>
                    <%= link_to edit_log_path(log.id), class: 'btn btn-primary' do %>
                      <i class="fa fa-pencil"></i>
                      Edit
                    <% end %>&nbsp;
                    <%= link_to log_path(log.id), class: 'btn btn-info info' do %>
                      <i class="fa fa-info-circle"></i>
                      Info
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </details>
      </td>
    </tr>

    <tr>
      <td>
        <label for="volunteer_phone">Phone</label>
      </td>
      <td>
        <div class="form-inline">
          <%= f.text_field(:phone, class: "form-control") %> with <%= f.select(:cell_carrier_id, CellCarrier.all.collect{ |cc| [cc.name,cc.id] },{include_blank: true}, {class: "form-control"}) %>
        </div>
      </td>
      </tr>
    </tr>

    <tr>
      <td>
        <label for="volunteer_email">
          Email
        </label>
      </td>
      <td><%= f.text_field(:email, class: "form-control") %></td>
    </tr>

    <tr>
      <td>
        <label for="volunteer_preferred_contact">
          Preferred Contact
        </label>
      </td>
      <td>
        <div class="form-inline">
          <%= f.select(:preferred_contact,[["Email","Email"],["Phone","Phone"],["Text","Text"]], {include_blank: true}, {class: "form-control"}) %>
        </div>
      </td>
    </tr>

    <tr>
      <td>
        <label for="">Receive From Robot</label>
      </td>
      <td>
        <div>
          <%= f.check_box(:sms_too) %>
          <label for="volunteer_sms_too">Text Messages</label>
        </div>
        <div>
          <%= f.check_box(:pre_reminders_too) %>
          <label for="volunteer_pre_reminders_too">Pre Pickup-Reminders</label>
        </div>
        <div>
          <%= f.check_box(:get_sncs_email) %>
          <label for="volunteer_get_sncs_email">SNCS Email</label>
        </div>
      </td>
    </tr>

    <tr>
      <td>
        <label for="volunteer_on_email_list">On Email List</label>
      </td>
      <td>
        <%= f.check_box(:on_email_list) %>
      </td>
    </tr>

    <tr>
      <td>
        <label for="volunteer_transport_type_id">Transport</label>
      </td>
      <td>
        <div class="form-inline">
          <%= f.select(:transport_type_id, TransportType.all.collect{ |tt| [tt.name,tt.id] },{include_blank: true}, {class: "form-control"}) %>
        </div>
      </td>
    </tr>

    <tr>
      <td>
        <label for="volunteer_has_car">Has Car</label>
      </td>
      <td><%= f.check_box(:has_car) %></td>
    </tr>

    <tr>
      <td>
        <label for="volunteer_pickup_prefs">Pickup Preferences</label>
      </td>
      <td class="form-fields"><%= f.text_area(:pickup_prefs, size: "30x6", class: "form-control") %></td>
    </tr>

    <% if current_volunteer.any_admin? %>
      <tr>
        <td>
          <label for="volunteer_admin_notes">Admin Notes</label>
        </td>
        <td><%= f.text_area(:admin_notes, size: "30x6", class: "form-control") %></td>
      </tr>
      <%= hidden_field_tag "volunteer[region_ids][]","" %>
      <tr>
        <td>
          <label for="">Region(s)</label>
        </td>
        <td>
          <% @my_admin_regions.each{ |r| %>
            <div class="col-sm-3">
              <%= check_box_tag "volunteer[region_ids][]", r.id, @volunteer.regions.include?(r) %>
              <label for=""><%= r.name %></label>
            </div>
          <% } unless @my_admin_regions.nil? %>
        </td>
      </tr>
      <tr>
        <td>
          <label for="volunteer_is_disabled">Account Disabled</label>
        </td>
        <td><%= f.check_box(:is_disabled) %></td>
      </tr>
    <% end %>

  </table>

  <%= submit_tag %>

<% end %>

app/views/volunteers/edit.html.erb
<h2>Edit Volunteer: <%= @volunteer.name %></h2>
<%= render partial: "form" %>

app/views/volunteers/home.html.erb
<% if @total_shifts_needing_cov > 0 %>
  <div class="alert fade in alert-danger" onclick="window.location='<%= open_logs_path %>';" style="cursor:pointer;">
    <i class="fa fa-exclamation-triangle"></i>
    <%= @total_shifts_needing_cov %> Shifts Need Covering Soon: <%= link_to "Pick one up here.", open_logs_path %>
  </div>
<% end %>

<% if @open_shift_count > 0 %>
  <div class="alert fade in alert-danger" onclick="window.location='<%= open_schedule_chains_path %>';" style="cursor:pointer;">
    <i class="fa fa-exclamation-triangle"></i>
    <%= @open_shift_count %> Shifts Need A Regular Volunteer: <%= link_to "Sign up here.", open_schedule_chains_path %>
  </div>
<% end %>

<% unless current_volunteer.main_region.nil? or current_volunteer.main_region.splash_html.blank? %>
  <div class="row bordered-bottom">
    <div class="col-sm-12">
      <h1> Welcome </h1>
      <%= raw current_volunteer.main_region.splash_html %>
    </div>
  </div>
<% end %>

<div class="row bordered-bottom">
  <div class="col-sm-6">
    <h2>Upcoming Pickups</h2>
    <% if @upcoming_pickups.length > 0 %>
      <table class="table table-striped">
        <tr>
          <th>Location</th>
          <th>Date</th>
          <th>Link</th>
        </tr>
        <% @upcoming_pickups.each do |shift| %>
           <tr class="bordered">
            <td>
              <% shift.logs.each{ |pickup| %>
                <%= link_to pickup.donor.try(:name), pickup.donor if pickup.donor.present? %> -&gt;
                  <% pickup.recipients.each do |recip| %>
                    <%= link_to recip.try(:name), recip if recip.present? %>
                  <% end %>
                <% unless pickup.food_types.empty? %>
                  <br />
                  <em>(<%= pickup.food_types.collect{ |ft| ft.name }.join(",") %>)</em>
                  <br />
                <% end %>
              <% } %>
            </td>
            <td>
              <%= readable_time_until shift.first_log %>
            </td>
            <td>
              <% unless shift.schedule_chain.nil? %>
                <button class="btn btn-info info" onclick="window.location='/schedule_chains/<%= shift.schedule_chain.id %>';">
                  <i class="fa fa-info-circle"></i>
                  Info
                </button>
              <% end %>
            </td>
          </tr>
        <% end %>
      </table>
    <% else %>
      <p>You have no upcoming pickups.</p>
    <% end %>
  </div>

  <div class="col-sm-6">
    <h2> To Do Pickup Reports </h2>
    <% if @to_do_reports.length > 0 %>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Location</th>
            <th>Date</th>
            <th></th>
          </tr>
        </thead>
        <% @to_do_reports.each do |report|
          next if report.recipients.empty?
        %>
          <tr class="bordered">
            <td>
              <%= link_to report.donor.try(:name), report.donor if report.donor.present? %> -&gt;
              <% report.recipients.each do |recip| %>
                <%= link_to recip.try(:name), recip if recip.present? %>
              <% end %>
              <% unless report.food_types.empty? %>
                <br />
                <em>(<%= report.food_types.collect{ |ft| ft.name }.join(",") %>)</em>
              <% end %>
            </td>
            <td>
              <%= readable_time_until report %>
            </td>
            <td>
              <button class="btn btn-danger fill" onclick="window.location='<%= edit_log_path(report) %>';">
                <i class="fa fa-star-half-o"></i>
                Fill
              </button>
            </td>
          </tr>
        <% end %>
      </table>
    <% else %>
      <p>You are up to date on all your pickup reports - nice work!</p>
    <% end %>
  </div>
</div><!-- /row -->

<div class="row bordered-bottom">
  <div class="col-sm-6">
    <h2>Shifts Needing Covering!</h2>
    <% if @shifts_needing_cov.length > 0 %>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Location</th>
            <th>Date</th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @shifts_needing_cov.each do |shift| %>

            <% next if shift.logs.all? { |log| log.donor.nil? || log.recipients.empty? } %>

            <tr class="bordered">
              <td>
                <% shift.logs.each do |log| %>
                  <% next if log.donor.nil? || log.recipients.empty? %>

                  <%= link_to log.donor.name, log.donor %> -&gt;
                  <% log.recipients.each do |recip| %>
                    <%=link_to recip.name, recip %>
                  <% end %>

                  <% unless log.food_types.empty? %>
                    <br />
                    <em>(<%= log.food_types.collect{ |type| type.name }.join(",") %>)</em>
                  <% end %>
                  <br />
                <% end %>
              </td>
              <td>
                <%= readable_time_until shift.first_log %>
              </td>
              <td>
                <button class="btn btn-primary take" onclick="window.location='<%= take_log_path(shift.first_log, ids: shift.log_ids) %>';">
                  <i class="fa fa-hand-rock-o"></i>
                  Take
                </button>
              </td>
              <td>
                <% if shift.schedule_chain.present? %>
                  <button class="btn btn-info info" onclick="window.location='/schedule_chains/<%= shift.schedule_chain.id %>';">
                    <i class="fa fa-info-circle"></i>
                    Info
                  </button>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% else %>
      <p>There are no shifts that need covering.</p>
    <% end %>
  </div>
</div>

<div class="row bordered-bottom">
  <div class="col-sm-6">
    <%= render partial: 'pickup_stats', locals: { presenter: @volunteer_stats_presenter.pickup_stats } %>
  </div>

  <div class="col-sm-6">
    <%= render partial: 'food_by_month', locals: { presenter: @volunteer_stats_presenter.lbs_by_month_graph } %>
  </div>

  <div class="col-sm-6">
    <h2> Your Info </h2>
    <table class="table table-striped">
      <thead>
        <tr>
          <td> Local time: </td>
          <td> <%= Time.zone.now %> </td>
        </tr>
      </thead>
      <tbody>
        <% if current_volunteer.region_admin? %>
          <tr>
            <td> Admin For: </td>
            <td>
              <%= @assigment_names %>
            </td>
          </tr>
        <% end %>
        <% if current_volunteer.super_admin? %>
          <tr>
            <td> Superpowers: </td>
            <td> You are omnipotent. Your power is without parallel. </td>
          </tr>
        <% end %>
        <tr>
          <td> Region(s): </td>
          <td> <%= current_volunteer.regions.collect{ |r| r.name }.join(", ") %> </td>
        </tr>
        <tr>
          <td> Preferred Transporation </td>
          <td> <%= current_volunteer.transport_type.nil? ? "unknown" : "a #{current_volunteer.transport_type.name}" %> </td>
        </tr>
        <tr>
          <td> Preferred Method of Contact </td>
          <td> <%= current_volunteer.preferred_contact.nil? ? "unknown" : current_volunteer.preferred_contact %> </td>
        </tr>
        <tr>
          <td> SMS Setup </td>
          <td> <%= current_volunteer.sms_too ? "Yes" : "No" %> </td>
        </tr>
        <tr>
          <td> SMS Active </td>
          <td>
            <% if current_volunteer.sms_email.nil? %>
            <p> No : Missing your cellphone carrier </p>
            <% elsif current_volunteer.sms_too %>
            <p> No : Missing your cellphone number </p>
            <% else %>
            <p> Yes </p>
            <% end %>
          </td>
        </tr>
        <tr>
          <td> Recieving pre-pick-up reminders </td>
          <td> <%= current_volunteer.pre_reminders_too ? "Yes" : "No" %> </td>
        </tr>
        <tr>
          <td> Recieving SNCS Emails </td>
          <td> <%= current_volunteer.get_sncs_email ? "Yes" : "No" %> </td>
        </tr>
        <tr>
          <td> Liability Waiver Signed </td>
          <td> <%= current_volunteer.waiver_signed ? "Yes" : "No" %> </td>
        </tr>

        <tr>
          <td> Change settings </td>
          <td> <a href="/volunteers/<%= current_volunteer.id %>/edit"> Click Here </a> </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

app/views/volunteers/index.html.erb
<h2><%= @header %></h2>

<% if @volunteers.length == 0 %>
  <p>No volunteers matching that criteria...</p>
<% else %>

  <table class="table" id="data_table">
    <thead>
      <tr>
        <th> Name </th>
        <th> Email </th>
        <th> Phone </th>
        <% if current_volunteer.any_admin? %>
          <th> Preferred Contact </th>
          <th> Transport </th>
          <th> Account Status </th>
          <th> Regions </th>
          <th> Admin Notes </th>
          <th> Member since </th>
          <th> Link </th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <%
      @volunteers.each do |v|
        row_bgcolor = nil
        if v.super_admin?
          row_bgcolor = "red"
        elsif v.any_admin?
          row_bgcolor = "pink"
        elsif v.needs_training?
          row_bgcolor = "lightgreen"
        end
      %>
      <tr <% unless row_bgcolor.nil? %>style="background: <%= row_bgcolor %>;"<% end %>>
        <td> <%= link_to v.name, v unless v.name.nil? %>
        <td> <a href="mailto:<%= v.email %>"><%= v.email %></a>
        <td> <%= v.phone %>
          <% if current_volunteer.any_admin? %>
          <td> <%= v.preferred_contact %>
          <td> <%= v.transport_type.nil? ? "?" : v.transport_type.name %> <%= "(has car)" if v.has_car %>
          <td> <% v.current_absences.each{ |a| %>
               Absent from <%= a.start_date %> to <%= a.stop_date %>
               <% } %>
          <td> <%= v.regions.collect{ |r| r.name }.join(", ") %>
          <% if current_volunteer.any_admin? %>
          <td> <%= word_wrap(v.admin_notes,:line_width => 20).gsub("\n","<br>").html_safe unless v.admin_notes.nil? %>
          <% end %>
          <td> <%= Time.at(v.created_at).strftime('%Y-%m-%d') %>
          <td>
            <% if current_volunteer.super_admin? || (current_volunteer.admin_region_ids & v.region_ids).length > 0 %>
              <%= link_to edit_volunteer_path(v), class: 'btn btn-primary' do %>
                <i class="fa fa-pencil"></i>
              <% end %>
               <%= link_to v, confirm: "Are you sure?", method: :delete, class: 'btn btn-danger' do %>
                <i class="fa fa-trash-o"></i>
               <% end %>
               <% unless v.active %>
                <br><%= link_to 'reactivate', reactivate_volunteer_path(v) %>
               <% end %>
               <% end %>
          <% end %>
      </tr>
      <% end %>
    </tbody>
  </table>
  <% if current_volunteer.any_admin? %>
    <br><br>
    <b>Key:</b> <span class="label" style="background: red">Admin</span>
    <span class="label" style="background: pink">Region Admin</span>
    <span class="label" style="background: lightgreen;">Needs Training (no completed shift)</span>
    <br><br>
    <b>Email List</b> <i class="muted">(you can copy and paste this into an email)</i>
    <blockquote><%= @volunteers.collect{ |v| v.email }.join(", ") %></blockquote>
  <% end %>

<% end %>

app/views/volunteers/new.html.erb
<h2>New Volunteer Account</h2>
<%= render partial: "form" %>