config/routes.rb
# frozen_string_literal: true

Webapp::Application.routes.draw do
  resources :assignments, only: [] do
    collection do
      get :knight
    end
  end

  resources :regions, except: [:show]

  resources :cell_carriers do as_routes end
  resources :transport_types do as_routes end

  resources :scale_types

  resources :absences do
    collection do
      get :all
    end
  end

  resources :logs do
    collection do
      get :by_day
      get :tardy
      get :last_ten
      get :open
      get :todo
      get :mine_past
      get :mine_upcoming
      get :being_covered
      get :new_absence
      get :create_absence
      get :receipt
      get :index
      get :edit
      get :update
      get :create
      get :destroy
      get :stats_service
      get :stats
      get :export
    end
    member do
      get :take
      get :leave
    end
  end

  resources :schedule_chains do
    collection do
      get :today
      get :tomorrow
      get :yesterday
      get :open
      get :open_old
      get :mine
      get :mine_old
      get :take
      get :leave
      get :index
      get :edit
      get :update
      get :create
      get :destroy
    end
    # member do
    #  get :show
    # end
  end

  resources :locations do
    collection do
      get :recipients
      get :hubs
      get :sellers
      get :buyers
      get :index
      get :edit
      get :update
      get :create
      get :destroy
    end

    member do
      get :hud
    end
  end

  devise_for :volunteers, :controllers => { :sessions => 'sessions' }

  resources :volunteers do
    collection do
      get :home
      get :unassigned
      get :shiftless
      get :shiftless_old
      get :active
      get :inactive
      get :need_training
      get :super_admin
      get :region_admin
      get :stats
      get :shift_stats
      get :switch_user
      get :knight
      get :index
      get :edit
      get :update
      get :create
      get :destroy
      get :assign
    end
    member do
      get :reactivate
    end
  end

  resource :waiver, only: [:new, :create]

  namespace :region_admin do
    resources :donors, only: [:index]

    resources :food_types, only: [:index, :new, :create, :edit, :update, :destroy]
  end

  devise_scope :volunteer do
    authenticated do
      root to: 'volunteers#home'
    end

    unauthenticated do
      root to: 'sessions#new', as: :unauthenticated_root
    end
  end
end

app/controllers/region_admin/donors_controller.rb
# frozen_string_literal: true

module RegionAdmin
  class DonorsController < ApplicationController
    before_filter :authenticate_volunteer!
    before_filter :authorize_region_admin!

    def index
      @locations = regional_donors
      @regions   = available_regions
    end

    private

    def regional_donors
      if current_volunteer.super_admin?
        Location.active.donors
      else
        Location.active.donors.regional(available_regions.map(&:id))
      end
    end

    def available_regions
      if current_volunteer.super_admin?
        Region.all
      else
        current_volunteer.assignments.collect{ |assignment| assignment.admin ? assignment.region : nil }.compact
      end
    end

    def authorize_region_admin!
      return if region_admin?
      redirect_to root_url, alert: 'Unauthorized'
    end

    def region_admin?
      current_volunteer.any_admin?
    end
  end
end

app/controllers/region_admin/food_types_controller.rb
# frozen_string_literal: true

module RegionAdmin
  class FoodTypesController < ApplicationController
    before_filter :authenticate_volunteer!
    before_filter :authorize_region_admin!

    def index
      @food_types = available_food_types

      respond_to do |format|
        format.html
        format.json { render json: @food_types.to_json }
      end
    end

    def new
      @food_type         = FoodType.new
      @available_regions = available_regions

      session[:my_return_to] = request.referer
    end

    def create
      context = RegionAdmin::CreateFoodType.call(
        volunteer: current_volunteer,
        params:    params[:food_type]
      )

      if context.success?
        flash[:notice] = 'Created successfully.'
        redirect_to session[:my_return_to].presence || region_admin_food_types_url
      else
        @food_type         = context.food_type
        @available_regions = available_regions

        flash.now[:alert] = 'There were errors saving the Food Type.'
        render :new
      end
    end

    def edit
      @food_type         = FoodType.find(params[:id])
      @available_regions = available_regions

      authorize!(:update, @food_type)

      session[:my_return_to] = request.referer
    end

    def update
      context = RegionAdmin::UpdateFoodType.call(
        volunteer:    current_volunteer,
        food_type_id: params[:id],
        params:       params[:food_type]
      )

      if context.success?
        flash[:notice] = 'Updated successfully.'
        redirect_to session[:my_return_to].presence || region_admin_food_types_url
      else
        @food_type = context.food_type

        flash.now[:alert] = 'There were errors saving the Food Type.'
        render :edit
      end
    end

    def destroy
      context = RegionAdmin::DeleteFoodType.call(
        volunteer:    current_volunteer,
        food_type_id: params[:id]
      )

      if context.success?
        flash[:notice] = 'Deleted successfully.'
      else
        flash[:alert] = 'There were errors deleting the Food Type.'
      end

      redirect_to(request.referrer)
    end

    private

    def available_food_types
      if current_volunteer.super_admin?
        FoodType.accessible_by(current_ability).active
      else
        FoodType.accessible_by(current_ability).active.regional(available_regions.map(&:id))
      end
    end

    def available_regions
      if current_volunteer.super_admin?
        Region.all
      else
        current_volunteer.assignments.collect{ |a| a.admin ? a.region : nil }.compact
      end
    end

    def authorize_region_admin!
      return if region_admin?
      redirect_unauthorized
    end

    def region_admin?
      current_volunteer.any_admin?
    end

    def redirect_unauthorized
      redirect_to root_url, alert: 'Unauthorized'
    end
  end
end

app/views/region_admin/food_types/edit.html.erb
<h2>Edit Food Type</h2>

<%= form_for [:region_admin, @food_type] do |f| %>
  <table class="table table-striped">
    <tr>
      <th>
        Region
      </th>
      <td>
        <%= @food_type.region.try(:name) %>
      </td>
    </tr>
    <tr>
      <th>
        <%= f.label :name %>
      </th>
      <td>
        <%= f.text_field :name %>
      </td>
    </tr>
  </table>

  <%= f.submit class: "btn btn-primary" %>
  <%= link_to "Cancel", region_admin_food_types_url, class: "btn btn-default" %>
<% end %>

app/views/region_admin/food_types/index.html.erb
<h2>Food Types</h2>

<div style="text-align: right;">
  <%= link_to "New Food Type", new_region_admin_food_type_url, class: "btn btn-primary" %>
</div>

<% if @food_types.empty? %>
  <p>No food types.</p>
<% else %>
  <table id="data_table" class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Region</th>
        <th>Link</th>
      </tr>
    </thead>

    <tbody>
      <% @food_types.each do |food_type| %>
        <tr>
          <td>
            <%= food_type.name %>
          </td>
          <td>
            <%= food_type.region.try(:name) %>
          </td>
          <td>
            <%= link_to edit_region_admin_food_type_url(food_type), class: 'btn btn-primary' do %>
              <i class="fa fa-pencil"></i>
              Edit
            <% end %>
            <br />
            <br />
            <%= link_to region_admin_food_type_url(food_type), confirm: "Are you sure?", method: :delete, class: 'btn btn-danger' do %>
              <i class="fa fa-trash-o"></i>
              Delete
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/region_admin/food_types/new.html.erb
<h2>New Food Type</h2>

<%= form_for [:region_admin, @food_type] do |f| %>
  <table class="table table-striped">
    <tr>
      <th>
        <%= f.label :region %>
      </th>
      <td>
        <%= f.select :region_id, @available_regions.map{|r| [r.name, r.id]} %>
      </td>
    </tr>
    <tr>
      <th>
        <%= f.label :name %>
      </th>
      <td>
        <%= f.text_field :name %>
      </td>
    </tr>
  </table>

  <%= f.submit class: "btn btn-primary" %>
  <%= link_to "Cancel", region_admin_food_types_url, class: "btn btn-default" %>
<% end %>